image: node:10.20.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - mkdir .cache_yarn && cd ./.cache_yarn

stages:
  - install
  - build
  - deploy
install_stage:
  stage: install
  script:
    - yarn install --cache-folder .cache_yarn
  artifacts:
    paths:
    - node_modules/
    - .cache_yarn/
  only:
    - dev
    - staging
    - master

build_stage_dev:
  stage: build
  environment: Development
  variables:
    REACT_APP_BASE_URL: "$API_BASE_URL_DEV"
    REACT_APP_FIREBASE_KEY: "$FIREBASE_DEPLOY_KEY_DEV"
    REACT_APP_FIREBASE_ID: "$FIREBASE_ID_DEV"
    REACT_APP_YANDEX_ID: "-1"
    REACT_APP_CONFERENCE_BASE_URL: "$CONFERENCE_BASE_URL_DEV"
    REACT_APP_CONFERENCE_CODE: "$CONFERENCE_CODE_DEV"
    REACT_APP_WEB_STUDENT_BASE_URL: "$WEB_STUDENT_BASE_URL_DEV"
    REACT_APP_PRESCRIPTION_URL: "$PRESCRIPTION_URL_DEV"
    REACT_APP_INTEREST_AREA_ID: "$INTEREST_AREA_ID_DEV"
  script:
    - REACT_ENV=development CI=false yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - dev
deploy_stage_dev:
  stage: deploy
  environment: Development
  only:
    - dev
  script:
    - yarn global add firebase-tools@9.22.0 --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_DEV -P default

    
build_staging:
  stage: build
  variables:
    REACT_APP_BASE_URL: "$API_BASE_URL_STAGE"
    REACT_APP_FIREBASE_KEY: "$FIREBASE_DEPLOY_KEY_STAGE"
    REACT_APP_FIREBASE_ID: "$FIREBASE_ID_STAGE"
    REACT_APP_YANDEX_ID: "-1"
    REACT_APP_CONFERENCE_BASE_URL: "$CONFERENCE_BASE_URL_DEV"
    REACT_APP_CONFERENCE_CODE: "$CONFERENCE_CODE_DEV"
    REACT_APP_WEB_STUDENT_BASE_URL: "$WEB_STUDENT_BASE_URL_STAGE"
    REACT_APP_PRESCRIPTION_URL: "$PRESCRIPTION_URL_STAGE"
    REACT_APP_INTEREST_AREA_ID: "$INTEREST_AREA_ID_PROD"
  script:
    - REACT_ENV=development CI=false yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - staging

deploy_stage:
  stage: deploy
  only:
    - staging
  script:
    - yarn global add firebase-tools@9.22.0 --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_STAGE -P admin-stage

build_stage_prod:
  stage: build
  variables:
    REACT_APP_BASE_URL: "$API_BASE_URL"
    REACT_APP_FIREBASE_KEY: "$FIREBASE_DEPLOY_KEY"
    REACT_APP_FIREBASE_ID: "$FIREBASE_ID"
    REACT_APP_CONFERENCE_BASE_URL: "$CONFERENCE_BASE_URL_PROD"
    REACT_APP_CONFERENCE_CODE: "$CONFERENCE_CODE_PROD"
    REACT_APP_WEB_STUDENT_BASE_URL: "$WEB_STUDENT_BASE_URL_PROD"
    REACT_APP_PRESCRIPTION_URL: "$PRESCRIPTION_URL_PROD"
    REACT_APP_INTEREST_AREA_ID: "$INTEREST_AREA_ID_PROD"
  script:
    - REACT_ENV=production CI=false yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - master

deploy_stage_prod:
  stage: deploy
  only:
    - master
  script:
    - yarn global add firebase-tools@9.22.0 --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY -P prod
