image: node:8.9.4

cache:
  key: yarnyarnyarngoodyarn
  paths:
  - mkdir .cache_yarn && cd ./.cache_yarn

stages:
  - install
  - build
  - test
  - deploy
install_stage:
  stage: install
  script:
    - yarn install --cache-folder .cache_yarn
  artifacts:
    paths:
    - node_modules/
  only:
    - qa
    - prod

build_stage_qa:
  stage: build
  script:
    - REACT_ENV=stage yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - qa
build_stage_prod:
  stage: build
  script:
    - REACT_ENV=production yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - prod
test_stage:
  stage: test
  script:
    - yarn test
  dependencies:
    - install_stage
  only:
    - qa
    - prod
deploy_stage_qa:
  stage: deploy
  only:
    - qa
  script:
    - yarn global add firebase-tools --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_STAGING --project stage
deploy_stage_prod:
  stage: deploy
  only:
    - prod
  script:
    - yarn global add firebase-tools --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_PRODUCTION --project production
