image: node:13.3.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - mkdir .cache_yarn && cd ./.cache_yarn

stages:
  - install
  - build
  - deploy
install_stage:
  stage: install
  script:
    - yarn install --cache-folder .cache_yarn
  artifacts:
    paths:
    - node_modules/
  only:
    - dev

build_stage_dev:
  stage: build
  variables:
    REACT_APP_BASE_URL: "$API_BASE_URL_DEV"
    REACT_APP_FIREBASE_KEY: "$FIREBASE_DEPLOY_KEY_DEV"
    REACT_APP_FIREBASE_ID: "$FIREBASE_ID_DEV"
    REACT_APP_YANDEX_ID: "-1"
  script:
    - REACT_ENV=development CI=false yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - dev
deploy_stage_dev:
  stage: deploy
  only:
    - dev
  script:
    - yarn global add firebase-tools --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_DEV