# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install NodeJS'

- script: |
    npm install -g yarn
    yarn install
  displayName: 'Install Yarn and dependencies'

# - bash: yarn test  --coverage
#   displayName: Unit test

- script: |
    REACT_ENV=stage yarn build
  displayName: 'Building QA'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/qa'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/**
      !**/node_modules/**
      
    TargetFolder: '$(build.artifactstagingdirectory)/qa'

- script: |
    REACT_ENV=production yarn build
  displayName: 'Building Prod'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/prod'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/**
      !**/node_modules/**
      
    TargetFolder: '$(build.artifactstagingdirectory)/prod'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: ugo_admin'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    name: 'ugo_admin'